# Generated by Django 6.0.4 on 2026-04-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mortalidad', 'Mortalidad Materna'), ('morbilidad', 'Morbilidad Materna Extrema')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='uploads/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('resumen', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
