# Generated by Django 6.0.4 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SivigilaImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('row_hash', models.CharField(max_length=64, unique=True)),
                ('event_hash', models.CharField(db_index=True, max_length=64)),
                ('caso_id', models.PositiveIntegerField()),
                ('numero_id', models.CharField(max_length=30)),
                ('tipo_identificacion', models.CharField(max_length=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Importación SIVIGILA',
                'verbose_name_plural': 'Importaciones SIVIGILA',
                'ordering': ['-creado_en'],
            },
        ),
    ]