# Generated by Django 6.0.4 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sivigilaimportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='archivo_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]